'use strict';

const { User, Good } = require('../sequelize').models;

module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert('tags', [
            {
                tagId: 1,
                tagName: 'Bất động sản',
            },
            {
                tagId: 2,
                tagName: 'Xe cộ',
            },
            {
                tagId: 3,
                tagName: 'Đồ điện tử',
            },
            {
                tagId: 4,
                tagName: 'Việc làm',
            },
            {
                tagId: 5,
                tagName: 'Thú cưng',
            },
            {
                tagId: 6,
                tagName: 'Đồ ăn, thực phầm các loại',
            },
            {
                tagId: 7,
                tagName: 'Tủ lạnh, máy lạnh, máy giặt',
            },
            {
                tagId: 8,
                tagName: 'Đồ gia dụng, nội thất, cây cảnh',
            },
            {
                tagId: 9,
                tagName: 'Mẹ và bé',
            },
            {
                tagId: 10,
                tagName: 'Thời trang, đồ dùng cá nhân',
            },
            {
                tagId: 11,
                tagName: 'Giải trí, Thể thao, Sở thích',
            },
            {
                tagId: 12,
                tagName: 'Đồ dùng văn phòng, công nông nghiệp',
            },
            {
                tagId: 13,
                tagName: 'Dịch vụ, Du lịch',
            },
        ]);

        await queryInterface.bulkInsert(
            'users',
            [
                {
                    userId: 1,
                    email: 'user1@example.com',
                    username: 'user1',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551001',
                    createdAt: new Date('2022-03-21T11:40:27.605Z'),
                    updatedAt: new Date('2022-03-21T11:40:27.605Z'),
                },
                {
                    userId: 2,
                    email: 'user2@example.com',
                    username: 'user2',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551002',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 3,
                    email: 'user3@example.com',
                    username: 'user3',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551003',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 4,
                    email: 'user4@example.com',
                    username: 'user4',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551004',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 5,
                    email: 'user5@example.com',
                    username: 'user5',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551005',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 6,
                    email: 'user6@example.com',
                    username: 'user6',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551006',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 7,
                    email: 'user7@example.com',
                    username: 'user7',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551007',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 8,
                    email: 'user8@example.com',
                    username: 'user8',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551008',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 9,
                    email: 'user9@example.com',
                    username: 'user9',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551009',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
                {
                    userId: 10,
                    email: 'user10@example.com',
                    username: 'user10',
                    password:
                        '$2b$10$St1d73RfkAoIs/kYOCSm/.ekQY2OCfD9tUF0BciGSX7wYnwJyK2XW',
                    address: null,
                    sdt: '0899551010',
                    createdAt: new Date('2022-03-21T12:42:13.910Z'),
                    updatedAt: new Date('2022-03-21T12:42:13.910Z'),
                },
            ]
        );

        // Dùng Good.bulkCreate mới trigger hook
        // Và phải thêm { individualHooks: true } ở cuối
        await Good.bulkCreate(
            [
                {
                    goodId: 1,
                    userId: 2,
                    name: 'Bình nước ABC',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 150000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:42:38.890Z'),
                    updatedAt: new Date('2022-03-21T12:42:38.890Z'),
                    tagId: 8,
                },
                {
                    goodId: 2,
                    userId: 1,
                    name: 'Điện thoại XYZ cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '119 Xuan Thuy, Cau Giay, Hanoi',
                    price: 1500000,
                    isSold: false,
                    state: 'secondhand',
                    createdAt: new Date('2022-03-21T12:42:51.908Z'),
                    updatedAt: new Date('2022-03-21T12:42:51.908Z'),
                    tagId: 3,
                },
                {
                    goodId: 3,
                    userId: 1,
                    name: 'Tủ lạnh Panasonic',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Phu Tho',
                    price: 4500000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 7,
                    brand: 'Panasonic',
                },
                {
                    goodId: 4,
                    userId: 3,
                    name: 'Tivi Sony',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 13490000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Sony',
                },
                {
                    goodId: 5,
                    userId: 3,
                    name: 'Máy lạnh Kangaroo',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 6990000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 7,
                    brand: 'Kangaroo',
                },
                {
                    goodId: 6,
                    userId: 3,
                    name: 'Máy giặt',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 7900000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 7,
                },
                {
                    goodId: 7,
                    userId: 3,
                    name: 'Tủ lạnh Toshiba Inverter 180 lít',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 5590000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 7,
                    brand: 'Toshiba',
                },
                {
                    goodId: 8,
                    userId: 3,
                    name: 'Nồi chiên không dầu Ava 5.5 lít',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 1690000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                },
                {
                    goodId: 9,
                    userId: 3,
                    name: 'Nồi cơm điện Sunhouse',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 690000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Sunhouse',
                },
                {
                    goodId: 10,
                    userId: 3,
                    name: 'Quạt điều hòa Sunhouse',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 4700000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Sunhouse',
                },
                {
                    goodId: 11,
                    userId: 3,
                    name: 'Quạt đứng Toshiba F-LSA20(H)VN',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 1490000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Toshiba',
                },
                {
                    goodId: 12,
                    userId: 3,
                    name: 'Bếp ga đôi Kangaroo',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 558900,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Kangaroo',
                },
                {
                    goodId: 13,
                    userId: 3,
                    name: 'Máy xay sinh tố Sunhouse SHD5112',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 349000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Sunhouse'
                },
                {
                    goodId: 14,
                    userId: 3,
                    name: 'Lò vi sóng Toshiba 20 lít',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 1650000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Toshiba',
                },
                {
                    goodId: 15,
                    userId: 3,
                    name: 'Robot hút bụi Xiaomi Robot Vacuum Gen 1',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hoan Kiem, Hanoi',
                    price: 7590000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                    brand: 'Xiaomi',
                },
                {
                    goodId: 16,
                    userId: 4,
                    name: 'Áo Hoodie Thời Trang Thu Đông Full Size',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 125000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 17,
                    userId: 4,
                    name: 'Áo len nam cổ tròn',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 250000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 18,
                    userId: 4,
                    name: 'Quần thể thao nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 99000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 19,
                    userId: 4,
                    name: 'Áo giữ nhiệt nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 60000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 20,
                    userId: 4,
                    name: 'Áo thun nam có cổ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 100000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 21,
                    userId: 4,
                    name: 'Áo chống nắng nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 89000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 22,
                    userId: 4,
                    name: 'Cà vạt đen bản nhỏ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 25000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 23,
                    userId: 4,
                    name: 'Quần Jogger nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 135000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 24,
                    userId: 4,
                    name: 'Áo sơ mi nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 150000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 25,
                    userId: 4,
                    name: 'Quần âu nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 250000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 26,
                    userId: 4,
                    name: 'Quần Jean nam',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hanoi',
                    price: 300000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 10,
                },
                {
                    goodId: 27,
                    userId: 5,
                    name: 'Xe máy Honda Vision 2021',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 34942000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'blue',
                },
                {
                    goodId: 28,
                    userId: 5,
                    name: 'Xe máy Honda SH Mode Thời trang CBS 2021',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 53890000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'red',
                },
                {
                    goodId: 29,
                    userId: 5,
                    name: 'Xe máy Honda Wave RSX Fi 110',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 24600000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'white',
                },
                {
                    goodId: 30,
                    userId: 5,
                    name: 'Xe máy Honda Winner X 2022',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 46000000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'red',
                },
                {
                    goodId: 31,
                    userId: 5,
                    name: 'Xe máy Honda Wave Alpha 2022',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 22760000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'red',
                },
                {
                    goodId: 32,
                    userId: 5,
                    name: 'Xe máy Honda Air Blade 125',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 42350000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Honda',
                    color: 'black',
                },
                {
                    goodId: 33,
                    userId: 5,
                    name: 'Yamaha Grande Cao cấp',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 41900000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Yamaha',
                    color: 'red',
                },
                {
                    goodId: 34,
                    userId: 5,
                    name: 'Xe Máy Yamaha Sirius Fi',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 21760000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Yamaha',
                    color: 'white',
                },
                {
                    goodId: 35,
                    userId: 5,
                    name: 'Yamaha Janus 2022',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Tp Hochiminh',
                    price: 34000000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 2,
                    brand: 'Yamaha',
                    color: 'grey',
                },
                {
                    goodId: 36,
                    userId: 6,
                    name: 'Xúc xích ăn liền cho chó mèo',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 3000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 37,
                    userId: 6,
                    name: 'Máng ăn cho gà',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 35000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 38,
                    userId: 6,
                    name: 'Bóng chạy cho chuột Hamster',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 55000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 39,
                    userId: 6,
                    name: 'Bàn chải lông cho chó mèo',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 64000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 40,
                    userId: 6,
                    name: 'PATE CHO MÈO WHISKAS vị cá biển 400G',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 37000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 41,
                    userId: 6,
                    name: 'Pate cho mèo Whiskas 85g',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 13000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 42,
                    userId: 6,
                    name: 'Pate Nekko cho mèo 70g',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 13000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 43,
                    userId: 6,
                    name: 'Xích chó inox loại to, đẹp',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 110000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 44,
                    userId: 6,
                    name: 'Rọ mõm da cho chó lớn',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 99000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 45,
                    userId: 6,
                    name: 'Sữa tắm SOS cho chó mèo',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Gia Lam, Hanoi',
                    price: 100000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 5,
                },
                {
                    goodId: 46,
                    userId: 7,
                    name: '10 quyển vở ô ly Hồng Hà',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 95000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                },
                {
                    goodId: 47,
                    userId: 7,
                    name: '10 quyển vở kẻ ngang Campus 80 trang',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 90000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                },
                {
                    goodId: 48,
                    userId: 7,
                    name: 'Vở kẻ ngang Hải Tiến 120 trang',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 10000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                },
                {
                    goodId: 49,
                    userId: 7,
                    name: 'Bút chì gỗ 2B',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 4000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                    color: 'yellow',
                },
                {
                    goodId: 50,
                    userId: 7,
                    name: 'Hộp 20 cây bút bi Thiên Long TL-027',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 69000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                    brand: 'Thiên Long',
                    color: 'blue',
                },
                {
                    goodId: 51,
                    userId: 7,
                    name: 'Tẩy bút chì Campus',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 7000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                },
                {
                    goodId: 52,
                    userId: 7,
                    name: 'Dập ghim Deli số 10',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Phong',
                    price: 40000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 12,
                    brand: 'Deli',
                    color: 'blue',
                },
                {
                    goodId: 53,
                    userId: 8,
                    name: 'Cây kim ngân để bàn',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Duong',
                    price: 79000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 8,
                },
                {
                    goodId: 54,
                    userId: 9,
                    name: 'Sữa Grow Plus đỏ Nutifood 900g',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Ba Trung, Hanoi',
                    price: 360000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 9,
                    brand: 'Nutifood',
                    color: 'red',
                },
                {
                    goodId: 55,
                    userId: 9,
                    name: 'Sữa Optimum Gold 1 900g',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Ba Trung, Hanoi',
                    price: 395000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 9,
                    brand: 'Vinamilk',
                },
                {
                    goodId: 56,
                    userId: 9,
                    name: 'Sữa bột Vinamilk Dielac Alpha Gold IQ 3 1,5 kg',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Ba Trung, Hanoi',
                    price: 440000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 9,
                    brand: 'Vinamilk',
                },
                {
                    goodId: 57,
                    userId: 9,
                    name: 'Tã quần Bobby Size M 76 miếng',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Hai Ba Trung, Hanoi',
                    price: 275000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 9,
                    brand: 'Bobby',
                },
                {
                    goodId: 58,
                    userId: 1,
                    name: 'Ipjhone 6 plus 128GB quốc tế cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 3000000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Apple',
                    color: 'white',
                },
                {
                    goodId: 59,
                    userId: 1,
                    name: 'Iphone 7 128GB cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 3900000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Apple',
                    color: 'rose-gold'
                },
                {
                    goodId: 60,
                    userId: 9,
                    name: 'Iphone 5s cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 1200000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Apple',
                    color: 'gold',
                },
                {
                    goodId: 61,
                    userId: 1,
                    name: 'Iphone 8 plus 64GB cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 5850000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Apple',
                    color: 'white',
                },
                {
                    goodId: 62,
                    userId: 1,
                    name: 'Ipad 9.7 inch 32GB cũ',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 6890000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Apple',
                },
                {
                    goodId: 63,
                    userId: 1,
                    name: 'Laptop cũ Dell Latitude E5450',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 7490000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Dell',
                    color: 'black',
                },
                {
                    goodId: 64,
                    userId: 1,
                    name: 'Laptop cũ Dell Vostro 5560',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 6490000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Dell',
                    color: 'grey'
                },
                {
                    goodId: 65,
                    userId: 1,
                    name: 'Laptop cũ Lenovo Thinkpad T440s i5 4300U',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 6600000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Lenovo',
                    color: 'black'
                },
                {
                    goodId: 66,
                    userId: 1,
                    name: 'Laptop cũ Asus X555LA',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 5500000,
                    isSold: true,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Asus',
                    color: 'black'
                },
                {
                    goodId: 67,
                    userId: 1,
                    name: 'Laptop cũ Sony Vaio SVE14 Core i3-3120M',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 3500000,
                    isSold: true,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'Sony',
                    color: 'white'
                },
                {
                    goodId: 68,
                    userId: 1,
                    name: 'Laptop cũ MSI Gaming GL60 7QF',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: '123 Xuan Thuy, Cau Giay, Hanoi',
                    price: 15500000,
                    isSold: false,
                    state: 'old',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 3,
                    brand: 'MSI',
                    color: 'grey'
                },
                {
                    goodId: 69,
                    userId: 10,
                    name: 'Bộ bài tây 52 lá',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Thai Binh',
                    price: 5000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 11,
                },
                {
                    goodId: 70,
                    userId: 10,
                    name: 'Bộ bài uno giấy cứng',
                    description:
                        'A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good A Test Good ',
                    address: 'Thai Binh',
                    price: 25000,
                    isSold: false,
                    state: 'new',
                    createdAt: new Date('2022-03-21T12:43:03.839Z'),
                    updatedAt: new Date('2022-03-21T12:43:03.839Z'),
                    tagId: 11,
                },
            ], {
            individualHooks: true
        }
        );

        await queryInterface.bulkInsert(
            'images', [
            {
                imageId: 3,
                link: "Tu_lanh_panasonic.jpg",
                goodImgId: 3,
            },
            {
                imageId: 4,
                link: "sony-kd-55x8000g-14-550x340.jpg",
                goodImgId: 4,
            },
            {
                imageId: 5,
                link: "May-dieu-hoa-inverter-Kangaroo-2.jpg",
                goodImgId: 5,
            },
            {
                imageId: 6,
                link: "DL.003233_FEATURE_71153.jpg",
                goodImgId: 6,
            },
            {
                imageId: 7,
                link: "tu_lanh_toshiba_inverter_180_lit_gr_b22vu_ukg_1_min.jpg",
                goodImgId: 7,
            },
            {
                imageId: 8,
                link: "ava-55k07a-55-lit-2.jpg",
                goodImgId: 8,
            },
            {
                imageId: 9,
                link: "10041815-noi-com-dien-sunhosue-1-2l-shd8217w-1.jpg",
                goodImgId: 9,
            },
            {
                imageId: 10,
                link: "10045129-quat-dieu-hoa-sunhouse-shd7727-1.jpg",
                goodImgId: 10,
            },
            {
                imageId: 11,
                link: "quat-toshiba-f-lsa20-h-vn.jpg",
                goodImgId: 11,
            },
            {
                imageId: 12,
                link: "bep-ga-doi-kangaroo-kg8g1c-1-300x300-1.jpg",
                goodImgId: 12,
            },
            {
                imageId: 13,
                link: "may_xay_sinh_to_shd5112.jpg",
                goodImgId: 13,
            },
            {
                imageId: 14,
                link: "Toshiba-ER-SM20(W1)VN-2.jpg",
                goodImgId: 14,
            },
            {
                imageId: 15,
                link: "robot-xiaomi-vacuum-gen1.jpg",
                goodImgId: 15,
            },
            {
                imageId: 16,
                link: "ao-hoodie-nam-dep.jpg",
                goodImgId: 16,
            },
            {
                imageId: 17,
                link: 'áo-len-nam-hà-nội.jpg',
                goodImgId: 17,
            },
            {
                imageId: 18,
                link: 'quan-the-thao-nam.jpg',
                goodImgId: 18,
            },
            {
                imageId: 19,
                link: 'ao-giu-nhiet-nam.jpg',
                goodImgId: 19,
            },
            {
                imageId: 20,
                link: 'ao-thun-nam-cao-cap.jpg',
                goodImgId: 20,
            },
            {
                imageId: 21,
                link: 'ao-chong-nang-nam-nu-cao-cap.jpg',
                goodImgId: 21,
            },
            {
                imageId: 22,
                link: 'ca-vat-den-ban-nho.jpg',
                goodImgId: 22,
            },
            {
                imageId: 23,
                link: 'quan-jogger-nam.jpg',
                goodImgId: 23,
            },
            {
                imageId: 24,
                link: 'ao-so-mi-nam-dep.jpeg',
                goodImgId: 24,
            },
            {
                imageId: 25,
                link: 'quan-au-nam.jpg',
                goodImgId: 25,
            },
            {
                imageId: 26,
                link: 'quan-jean-nam.jpg',
                goodImgId: 26,
            },
            {
                imageId: 27,
                link: 'xe-may-honda-vision-2021.png',
                goodImgId: 27,
            },
            {
                imageId: 28,
                link: 'sh-mode-thoi-trang-cbs-1-a75f.png',
                goodImgId: 28,
            },
            {
                imageId: 29,
                link: 'wave-rsx-fi-110.png',
                goodImgId: 29,
            },
            {
                imageId: 30,
                link: 'honda-winner-x-tieu-chuan-2-21ee.jpg',
                goodImgId: 30,
            },
            {
                imageId: 31,
                link: 'honda-wave-alpha-3-120c.png',
                goodImgId: 31,
            },
            {
                imageId: 32,
                link: 'db-125-honda-air-blade-e73c.png',
                goodImgId: 32,
            },
            {
                imageId: 33,
                link: 'yamaha-grande-deluxe-3-c615.png',
                goodImgId: 33,
            },
            {
                imageId: 34,
                link: 'xe-may-yamaha-sirius-fi-phanh-co.png',
                goodImgId: 34,
            },
            {
                imageId: 35,
                link: 'yamaha-janus-125cc.jpg',
                goodImgId: 35,
            },
            {
                imageId: 36,
                link: 'xuc-xich-an-lien-cho-cho-meo.jpg',
                goodImgId: 36,
            },
            {
                imageId: 37,
                link: 'mang-an-chong-boi-cho-ga-3.jpg',
                goodImgId: 37,
            },
            {
                imageId: 38,
                link: 'bong-chay-cho-chuot-hamster.jpg',
                goodImgId: 38,
            },
            {
                imageId: 39,
                link: 'ban-chai-long-cho-meo.jpg',
                goodImgId: 39,
            },
            {
                imageId: 40,
                link: 'pate-cho-meo-whiskas-vi-ca-bien-400g',
                goodImgId: 40,
            },
            {
                imageId: 41,
                link: 'Pate-cho-meo-whiskas-85g.jpg',
                goodImgId: 41,
            },
            {
                imageId: 42,
                link: 'pate-cho-meo-nekko.jpg',
                goodImgId: 42,
            },
            {
                imageId: 43,
                link: 'xich-cho-inox-loai-to.jpg',
                goodImgId: 43,
            },
            {
                imageId: 44,
                link: 'ro-mom-da-cho-cho.jpg',
                goodImgId: 44,
            },
            {
                imageId: 45,
                link: 'Sua-tam-sos-cho-cho-meo.jpg',
                goodImgId: 45,
            },
            {
                imageId: 46,
                link: 'vo-o-ly-hong-ha.jpg',
                goodImgId: 46,
            },
            {
                imageId: 47,
                link: 'vo-ke-ngang-campus-80-trang.jpg',
                goodImgId: 47,
            },
            {
                imageId: 48,
                link: 'vo-ke-ngang-hai-tien-120-trang.jpg',
                goodImgId: 48,
            },
            {
                imageId: 49,
                link: 'but-chi-go-2b-staedtler.jpg',
                goodImgId: 49,
            },
            {
                imageId: 50,
                link: 'hop-20-cay-but-bi-thien-long-tl-027.jpg',
                goodImgId: 50,
            },
            {
                imageId: 51,
                link: 'tay-but-chi-campus.jpg',
                goodImgId: 51,
            },
            {
                imageId: 52,
                link: 'dap-ghim-so-10-bam-15-to-giay-deli-271.jpg',
                goodImgId: 52,
            },
            {
                imageId: 53,
                link: 'cay-kim-ngan-tam-loc-phat-tai.jpg',
                goodImgId: 53,
            },
            {
                imageId: 54,
                link: 'sua-grow-plus-do-900g.jpg',
                goodImgId: 54,
            },
            {
                imageId: 55,
                link: 'vinamilk-optimum-gold-1-900g.jpg',
                goodImgId: 55,
            },
            {
                imageId: 56,
                link: 'sua-bot-vinamilk-dielac-alpha-gold-iq-3-15kg-1-2-tuoi.jpg',
                goodImgId: 56,
            },
            {
                imageId: 57,
                link: 'bim-ta-quan-bobby-1805-size-m-76-mieng-6-10kg.jpg',
                goodImgId: 57,
            },
            {
                imageId: 58,
                link: 'iphone-6-plus-bac-900-19515f.jpg',
                goodImgId: 58,
            },
            {
                imageId: 59,
                link: 'iphone-7-rose-gold.jpg',
                goodImgId: 59,
            },
            {
                imageId: 60,
                link: 'apple-iphone-5s-gold-3d-model-max-obj.jpg',
                goodImgId: 60,
            },
            {
                imageId: 61,
                link: 'iphone-8-plus-trang.jpg',
                goodImgId: 61,
            },
            {
                imageId: 62,
                link: 'ipad-2018-32gb.jpg',
                goodImgId: 62,
            },
            {
                imageId: 63,
                link: 'LAPTOP-CU-DELL-LATITUDE-E5450-3.jpg',
                goodImgId: 63,
            },
            {
                imageId: 64,
                link: 'laptop-cu-dell-vostro-5560-core-i5-3230m-4gb-hdd-1-tb-15-6-inch-hd-4.jpg',
                goodImgId: 64,
            },
            {
                imageId: 65,
                link: 'lenovo-thinkpad-t440s-2-laptop247hn-large.jpg',
                goodImgId: 65,
            },
            {
                imageId: 66,
                link: 'laptop-cu-asus-X555LA-600x540.jpg',
                goodImgId: 66,
            },
            {
                imageId: 67,
                link: 'Sony-Vaio-SVE14-500x500.jpg',
                goodImgId: 67,
            },
            {
                imageId: 68,
                link: 'laptop-cu-msi-gaming-gl62-core_i7-17.jpg',
                goodImgId: 68,
            },
            {
                imageId: 69,
                link: 'bo-bai-tay-double-k-52-la.jpg',
                goodImgId: 69,
            },
            {
                imageId: 70,
                link: 'bo-bai-uno-giay-cung.jpg',
                goodImgId: 70,
            },

        ])

        await queryInterface.bulkInsert('comments', [
            {
                commentId: 1,
                goodId: 1,
                userId: 1,
                content:
                    'Test Comment Content Test Comment Content Test Comment Content',
                createdAt: new Date('2022-03-21T12:47:03.839Z'),
                updatedAt: new Date('2022-03-21T12:47:03.839Z'),
            },
            {
                commentId: 2,
                goodId: 1,
                userId: 1,
                content: 'Test Comment Number 2',
                createdAt: new Date('2022-03-21T12:49:03.839Z'),
                updatedAt: new Date('2022-03-21T12:49:03.839Z'),
            },
            {
                commentId: 3,
                goodId: 2,
                userId: 2,
                content: 'Trông cũ quá!!!',
                createdAt: new Date('2022-03-21T12:54:30.839Z'),
                updatedAt: new Date('2022-03-21T12:54:30.839Z'),
            },
            {
                commentId: 4,
                goodId: 1,
                userId: 2,
                content: 'Mại zô Mại zô',
                createdAt: new Date('2022-03-21T12:57:30.839Z'),
                updatedAt: new Date('2022-03-21T12:57:30.839Z'),
            },
        ]);

        const user1 = await User.findOne({ where: { userId: 1 } });
        const user2 = await User.findOne({ where: { userId: 2 } });

        await user2.addFollower(user1);

        const firstGood = await Good.findOne({ where: { goodId: 1 } });
        await user1.addBookmarkedGood(firstGood);
        await user2.addBookmarkedGood(firstGood);

        // Chat
        await queryInterface.bulkInsert('conversations', [
            {
                conversationId: 1,
                username1: 'user1',
                username2: 'user2',
                createdAt: new Date('2022-03-21T12:42:13.910Z'),
                updatedAt: new Date('2022-03-21T12:42:13.910Z'),
            },
        ]);

        await queryInterface.bulkInsert('chatcontexts', [
            {
                chatContextId: 1,
                conversationId: 1,
                username: 'user1',
                context: 'Hello',
                createdAt: new Date('2022-03-21T12:42:15.910Z'),
                updatedAt: new Date('2022-03-21T12:42:15.910Z'),
            },
            {
                chatContextId: 2,
                conversationId: 1,
                username: 'user2',
                context: 'Hello',
                createdAt: new Date('2022-03-21T12:42:16.910Z'),
                updatedAt: new Date('2022-03-21T12:42:16.910Z'),
            },
            {
                chatContextId: 3,
                conversationId: 1,
                username: 'user1',
                context: 'How are you?',
                createdAt: new Date('2022-03-21T12:42:17.910Z'),
                updatedAt: new Date('2022-03-21T12:42:17.910Z'),
            },
            {
                chatContextId: 4,
                conversationId: 1,
                username: 'user2',
                context: "I'm fine, thank you!",
                createdAt: new Date('2022-03-21T12:42:18.910Z'),
                updatedAt: new Date('2022-03-21T12:42:18.910Z'),
            },
            {
                chatContextId: 5,
                conversationId: 1,
                username: 'user2',
                context: 'And you?',
                createdAt: new Date('2022-03-21T12:42:19.910Z'),
                updatedAt: new Date('2022-03-21T12:42:19.910Z'),
            },
        ]);
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('tags');
        await queryInterface.bulkDelete('users');
        await queryInterface.bulkDelete('goods');
        await queryInterface.bulkDelete('comments');
        await queryInterface.bulkDelete('images');
        await queryInterface.bulkDelete('conversations');
        await queryInterface.bulkDelete('chatcontexts');
        await queryInterface.bulkDelete('buygoods');
        await queryInterface.bulkDelete('sqlite_sequence'); // auto increment table
    },
};
