const actionTypes = Object.freeze({
  LOGIN_BY_JWT_SUCCESS: "LOGIN_BY_JWT_SUCCESS",
  LOGIN_BY_JWT_FAILED: "LOGIN_BY_JWT_FAILED",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",
  GET_ALL_PRODUCT_LOADING: "GET_ALL_PRODUCT_LOADING",

  BUY_PRODUCTS_SUCCESS: "BUY_PRODUCTS_SUCCESS",
  BUY_PRODUCTS_FAILED: "BUY_PRODUCT_FAILED",

  FETCH_SEARCH_PRODUCT_SUCCESS: "FETCH_SEARCH_PRODUCT_SUCCESS",
  FETCH_SEARCH_PRODUCT_FAILED: "FETCH_SEARCH_PRODUCT_FAILED",
});

export default actionTypes;
