name: Tét server CI

on:
  push:
    paths:
      - "server/**"
    branches: [main]
  pull_request:
    paths:
      - "server/**"
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./server

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"
      - name: Cài đặt dependencies
        run: npm ci
      - name: Đảm bảo seed vẫn chạy được
        run: npm run seed
      - name: Chạy test Jest
        run: npm test
